<?php
$gejala = [
    "G01" => "Demam, gemetar, sempoyongan, lemah, ambruk",
    "G02" => "Kematian mendadak",
    "G03" => "Sulit bernapas",
    "G04" => "Air liur terus menerus",
    "G05" => "Tubuh gemetar",
    "G06" => "Kurus, batuk, nafsu makan turun",
    "G07" => "Anemia, kurus, bulu rontok, busung, mati",
    "G08" => "Getah dari hidung dan mata",
    "G09" => "Sempoyongan, kejang, berputar (mubeng)",
    "G10" => "Demam 40-41°C",
    "G11" => "Lemah, kurus",
    "G12" => "Gemetar, sempoyongan, torticolis, agresif",
    "G13" => "Mati 4–13 hari setelah gejala",
    "G14" => "Kerak kulit keabuan",
    "G15" => "Menggosok badan, menggigit tubuh sendiri",
    "G16" => "Lemah, tidak bisa berdiri",
    "G17" => "Cairan dari mata dan hidung",
    "G18" => "Produksi susu turun/habis",
    "G19" => "Badan kurus",
    "G20" => "Bulu kusam, berdiri",
    "G21" => "Diare atau sembelit",
    "G22" => "Mata berair, kemerahan",
    "G23" => "Kornea keruh",
    "G24" => "Ambing bengkak",
    "G25" => "Susu berubah, ada endapan/jonjot",
    "G26" => "Gugur (betina), testis/lutut bengkak (jantan)",
    "G27" => "Plasenta tebal, testis bernanah",
    "G28" => "Tidak nafsu makan (anoreksia)",
    "G29" => "Susu turun drastis 2–3 hari",
    "G30" => "Air liur menggantung/berbusa",
    "G31" => "Sering berbaring",
    "G32" => "Luka pada kuku, kuku lepas",
    "G33" => "Gigi menggeretak, gosok mulut, tendang kaki",
    "G34" => "Air liur berlebihan + busa"
];
?>